### ISSUE TITLE
How to use tearing plugin in SOFA

### ISSUE THREAD

**Issue by xhtsansiro** [InfinyTech3D/Tearing#37]
Hi, 

I have a question about how to use tearing plugin in SOFA. 

I finished the settings of SOFA and tearing plugin. Both are of the same version v23.12. But I am not really sure about how to use tearing plugin.

Is it correct that I put `<RequiredPlugin name="tearing"/>` and
`<TearingEngine name="TearingEngine" input_position="@Mo.position" stressThreshold="0.2" step="20" nbFractureMax="40" showFracturePath="1"/>`
inside the scn file, such that the tearing plugin is activated in SOFA? Is the parameter adjustment of tearing engine only possible inside scn file?

Best.

**Comment by xhtsansiro** [comment]
Can you please tell me which scn file is the animation in README? 

Best Regards,

**Comment by xhtsansiro** [comment]
The gif file in README is exactly what I aim to do. So I wonder how is the scn setting of this scene. It would be pretty nice if you could give some hints on that.

Best Regards.

**Comment by xhtsansiro** [comment]
Hi,

The gif file in README is exactly what I aim to do. So I wonder how is the scn setting of this scene. It would be pretty nice if you could give some hints on that.

I try to use the tearing plugin under the scene "SquareTissue_04_cornerPressure.scn". I expect the surface is torn when the stress is bigger than the stressThreshold. But when the stress is bigger than threshold, the program throws an segmentation fault and quit automatically. What do I need to adjust in code to achieve the desired effect.

Best Regards.

**Comment by epernod** [comment]
Hi,

yes you need to add the plugin in your scene as you mention it: ```<RequiredPlugin name="tearing"/>```
Then on how to use it, you can check the different examples or there is also a small [documentation](https://github.com/InfinyTech3D/Tearing/blob/main/doc/TearingPluginDocumentation.pdf)

To use the mouse, you need to make sure your tissue under gravity doesn't reach the fracture criteria and then use the mouse to tear it. 
We know that several bugs have been reported, unfortunately we have limited budget to support this plugin and is right now in low priority.
We will restore the behavior as soon as we can! If you would like to speedup the work do not hesitate to [sponsor us](https://github.com/sponsors/InfinyTech3D)! 

Best regards,

**Comment by xhtsansiro** [comment]
Hi @epernod 

Thank you for your reply. I read through issues raised by other people.  [Issue #4592](https://github.com/sofa-framework/sofa/discussions/4592) is similar to what I encountered. 

Following pic. is the setting of the scene, where I set the stressThreshold to 5.53. What I expected is the surface tissue is torn when the maxStress reaches stressThreshold.  And when I pull the tissue by shift + left mouse clicking, the surface deforms but is not torn, and the maxStress is increasing. As soon as the maxStress reaches the stressThreshold, the program crashes with a segmentation fault like what is described in issue 4592.  Is this one of the issue what you mean by "the mouse support has not been addressed" in #4592? 

![1712829433279](https://github.com/InfinyTech3D/Tearing/assets/55890308/e3376e1a-53e9-426e-b9cb-87210f6323e9)

In the README file of [tearing plugin](https://github.com/InfinyTech3D/tearing/), the gif shows the tissue tearing process. Is the tearing done by using mouse or some other devices? Is the scn file of this demo provided in the code repository?

Best Regards.

**Comment by epernod** [comment]
Hi
thank you for the report. Could you precise which version of SOFA and the Tearing plugin you are using?
Could you also provide the crash log from the console.

**Comment by xhtsansiro** [comment]
Hi @epernod 

The sofa and tearing plugin version I use are both v23.12.
The crash log is as follow:

[ERROR]   [TriangleSetGeometryAlgorithms(GeomAlgo)] Edges don't intersect themself.

########## SIG 11 - SIGSEGV: segfault ##########
  sofa::helper::BackTrace::sig(int)
  sofa::component::topology::container::dynamic::TriangleSetGeometryAlgorithms<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::SplitAlongPath(unsigned int, sofa::type::Vec<3u, double>&, unsigned int, sofa::type::Vec<3u, double>&, sofa::type::vector<sofa::geometry::ElementType, sofa::type::CPUMemoryManager<sofa::geometry::ElementType> >&, sofa::type::vector<unsigned int, sofa::type::CPUMemoryManager<unsigned int> >&, sofa::type::vector<sofa::type::Vec<3u, double>, sofa::type::CPUMemoryManager<sofa::type::Vec<3u, double> > >&, sofa::type::vector<unsigned int, sofa::type::CPUMemoryManager<unsigned int> >&, double, double)
  sofa::component::TearingAlgorithms<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::splitting(int, int, sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, int, int, sofa::type::vector<sofa::geometry::ElementType, sofa::type::CPUMemoryManager<sofa::geometry::ElementType> >, sofa::type::vector<unsigned int, sofa::type::CPUMemoryManager<unsigned int> >, sofa::type::vector<sofa::type::Vec<3u, double>, sofa::type::CPUMemoryManager<sofa::type::Vec<3u, double> > >, sofa::type::vector<unsigned int, sofa::type::CPUMemoryManager<unsigned int> >&)
  sofa::component::TearingAlgorithms<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::algoFracturePath(sofa::type::Vec<3u, double>, unsigned int, sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, unsigned int, sofa::type::Vec<3u, double>, sofa::type::vector<sofa::type::Vec<3u, double>, sofa::type::CPUMemoryManager<sofa::type::Vec<3u, double> > > const&)
  sofa::component::engine::TearingEngine<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::algoFracturePath()
  sofa::simulation::PropagateEventVisitor::processNodeTopDown(sofa::simulation::Node*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::doExecuteVisitor(sofa::simulation::Visitor*, bool)
  sofa::simulation::DefaultAnimationLoop::propagateAnimateEndEvent(sofa::core::ExecParams const*, double) const
  sofa::simulation::DefaultAnimationLoop::step(sofa::core::ExecParams const*, double)
  sofa::simulation::node::animate(sofa::simulation::Node*, double)
  sofa::gui::qt::RealGUI::step()
  QTimer::timeout(QTimer::QPrivateSignal)
  QObject::event(QEvent*)
  QApplicationPrivate::notify_helper(QObject*, QEvent*)
  QCoreApplication::notifyInternal2(QObject*, QEvent*)
  QTimerInfoList::activateTimers()
  g_main_context_dispatch
  g_main_context_iteration
  QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)
  QCoreApplication::exec()
  sofa::gui::qt::RealGUI::mainLoop()
  sofa::gui::common::GUIManager::MainLoop(boost::intrusive_ptr<sofa::simulation::Node>, char const*)
  __libc_start_main
Segmentation fault (core dumped)

**Comment by xhtsansiro** [comment]
@epernod 

I want to point it out that "Edges don't intersect themself" is not always displayed in console when sofa crashes. 
the logs are as follow:
[INFO]    [SceneCheckerVisitor] Finished validating node "root".

########## SIG 11 - SIGSEGV: segfault ##########
  sofa::helper::BackTrace::sig(int)
  sofa::component::topology::container::dynamic::TriangleSetGeometryAlgorithms<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::SplitAlongPath(unsigned int, sofa::type::Vec<3u, double>&, unsigned int, sofa::type::Vec<3u, double>&, sofa::type::vector<sofa::geometry::ElementType, sofa::type::CPUMemoryManager<sofa::geometry::ElementType> >&, sofa::type::vector<unsigned int, sofa::type::CPUMemoryManager<unsigned int> >&, sofa::type::vector<sofa::type::Vec<3u, double>, sofa::type::CPUMemoryManager<sofa::type::Vec<3u, double> > >&, sofa::type::vector<unsigned int, sofa::type::CPUMemoryManager<unsigned int> >&, double, double)
  sofa::component::TearingAlgorithms<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::splitting(int, int, sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, int, int, sofa::type::vector<sofa::geometry::ElementType, sofa::type::CPUMemoryManager<sofa::geometry::ElementType> >, sofa::type::vector<unsigned int, sofa::type::CPUMemoryManager<unsigned int> >, sofa::type::vector<sofa::type::Vec<3u, double>, sofa::type::CPUMemoryManager<sofa::type::Vec<3u, double> > >, sofa::type::vector<unsigned int, sofa::type::CPUMemoryManager<unsigned int> >&)
  sofa::component::TearingAlgorithms<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::algoFracturePath(sofa::type::Vec<3u, double>, unsigned int, sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, unsigned int, sofa::type::Vec<3u, double>, sofa::type::vector<sofa::type::Vec<3u, double>, sofa::type::CPUMemoryManager<sofa::type::Vec<3u, double> > > const&)
  sofa::component::engine::TearingEngine<sofa::defaulttype::StdVectorTypes<sofa::type::Vec<3u, double>, sofa::type::Vec<3u, double>, double> >::algoFracturePath()
  sofa::simulation::PropagateEventVisitor::processNodeTopDown(sofa::simulation::Node*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*, std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
  sofa::simulation::graph::DAGNode::doExecuteVisitor(sofa::simulation::Visitor*, bool)
  sofa::simulation::DefaultAnimationLoop::propagateAnimateEndEvent(sofa::core::ExecParams const*, double) const
  sofa::simulation::DefaultAnimationLoop::step(sofa::core::ExecParams const*, double)
  sofa::simulation::node::animate(sofa::simulation::Node*, double)
  sofa::gui::qt::RealGUI::step()
  QTimer::timeout(QTimer::QPrivateSignal)
  QObject::event(QEvent*)
  QApplicationPrivate::notify_helper(QObject*, QEvent*)
  QCoreApplication::notifyInternal2(QObject*, QEvent*)
  QTimerInfoList::activateTimers()
  g_main_context_dispatch
  g_main_context_iteration
  QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)
  QCoreApplication::exec()
  sofa::gui::qt::RealGUI::mainLoop()
  sofa::gui::common::GUIManager::MainLoop(boost::intrusive_ptr<sofa::simulation::Node>, char const*)
  __libc_start_main
Segmentation fault (core dumped)

**Comment by xhtsansiro** [comment]
> Hi,
> 
> yes you need to add the plugin in your scene as you mention it: `<RequiredPlugin name="tearing"/>` Then on how to use it, you can check the different examples or there is also a small [documentation](https://github.com/InfinyTech3D/Tearing/blob/main/doc/TearingPluginDocumentation.pdf)
> 
> To use the mouse, you need to make sure your tissue under gravity doesn't reach the fracture criteria and then use the mouse to tear it. We know that several bugs have been reported, unfortunately we have limited budget to support this plugin and is right now in low priority. We will restore the behavior as soon as we can! If you would like to speedup the work do not hesitate to [sponsor us](https://github.com/sponsors/InfinyTech3D)!
> 
> Best regards,

Hi @epernod , 

I just checked the sponsor list. I want to sponsor to get your guidance on the membrane tearing topic. Let's say, creating a scene and performing surface tearing under this scene. Is it possible when I sponsor 500$ one time ?

Best Regards,

**Comment by xhtsansiro** [comment]
> Hi,
> 
> yes you need to add the plugin in your scene as you mention it: `<RequiredPlugin name="tearing"/>` Then on how to use it, you can check the different examples or there is also a small [documentation](https://github.com/InfinyTech3D/Tearing/blob/main/doc/TearingPluginDocumentation.pdf)
> 
> To use the mouse, you need to make sure your tissue under gravity doesn't reach the fracture criteria and then use the mouse to tear it. We know that several bugs have been reported, unfortunately we have limited budget to support this plugin and is right now in low priority. We will restore the behavior as soon as we can! If you would like to speedup the work do not hesitate to [sponsor us](https://github.com/sponsors/InfinyTech3D)!
> 
> Best regards,

Hi @epernod ,

I just checked the sponsor guidelines. I want to sponsor to get your guidance on the membrane tearing topic. Let's say, creating a scene and performing surface tearing by using mouse or any other devices. Is it possible when I sponsor 500$ one time ?

Best Regards,

**Comment by xhtsansiro** [comment]
Hi, @epernod 

I would like to ask you about the procedure of this donation.

![1713436587455](https://github.com/InfinyTech3D/Tearing/assets/55890308/deb90e6c-662d-4a7d-82a9-f0b718058093)

Should I donate first and we communicate the topic of the support session? Or first fixing the topic and then donating. I don't know how to contact you by email. My email address is xhtsansiro@live.com

Looking forward to your feedback!

**Comment by epernod** [comment]
Thank you,
your sponsor has well been received!
